/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      spacing: {
        '0': '0px',
        '4': 'var(--spacing-4)',
        '8': 'var(--spacing-8)',
        '12': 'var(--spacing-12)',
        '16': 'var(--spacing-16)',
        '24': 'var(--spacing-24)',
        '32': 'var(--spacing-32)',
        '48': 'var(--spacing-48)',
        '64': 'var(--spacing-64)',
        '96': 'var(--spacing-96)',
        '128': 'var(--spacing-128)',
      },
      borderRadius: {
        'none': '0',
        '4': 'var(--radius-4)',
        '8': 'var(--radius-8)',
        '12': 'var(--radius-12)',
        '16': 'var(--radius-16)',
        '24': 'var(--radius-24)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'inner': 'var(--shadow-inner)',
        'focus': 'var(--shadow-focus)',
      },
      zIndex: {
        'base': 'var(--z-base)',
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'drawer': 'var(--z-drawer)',
        'modal': 'var(--z-modal)',
        'popover': 'var(--z-popover)',
        'toast': 'var(--z-toast)',
        'drag': 'var(--z-drag)',
        'skip': 'var(--z-skip)',
      },
      transitionDuration: {
        'instant': 'var(--duration-instant)',
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow': 'var(--duration-slow)',
        'slower': 'var(--duration-slower)',
        'enter': 'var(--duration-enter)',
        'exit': 'var(--duration-exit)',
      },
      transitionTimingFunction: {
        'in': 'var(--easing-in)',
        'out': 'var(--easing-out)',
        'in-out': 'var(--easing-in-out)',
        'spring': 'var(--easing-spring)',
        'dramatic': 'var(--easing-dramatic)',
        'snap': 'var(--easing-snap)',
      },
    },
  },
  plugins: [],
}
