import { Router } from "express";
import { getProjects, getProject, createProject, getTeams, getTeam, createTeam } from "../controllers/orgController";
import { authMiddleware } from "../middleware/auth";
import { requireManager } from "../middleware/roleGuard";
const router = Router();
router.use(authMiddleware);
router.get("/projects", getProjects);
router.get("/projects/:id", getProject);
router.post("/projects", requireManager, createProject);
router.get("/teams", getTeams);
router.get("/teams/:id", getTeam);
router.post("/teams", requireManager, createTeam);
export default router;
